name: Artifact upload and download
on: ["push","pull_request", "workflow_dispatch"]
jobs:
    upload-basic:
        runs-on: ubuntu-slim
        steps:
            - run: |
                mkdir -p out
                echo "Build and upload" > out/build_file.txt
            - uses: actions/upload-artifact@v4
              with:
                name: upload-basic
                path: out/
    download-basic:
        runs-on: ubuntu-slim
        needs: upload-basic
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: upload-basic
                path: downloaded/
            - run: |
                ls -R downloaded/
                cat downloaded/*
    
    upload-multiple:
        runs-on: ubuntu-slim
        steps:
            - run: |
                mkdir -p out
                echo "Build number ${{github.sha}}" >> out/build_${{github.sha}}.txt
                echo "Build number ${{github.sha}}" >> out/build_${{github.sha}}.txt
                echo "Build number ${{github.sha}}" >> out/build_${{github.sha}}.txt
                echo "Build number 1" >> out/build_1.txt
                echo "Build number 2" >> out/build_2.txt
                echo "Build number 3" >> out/build_3.txt
            - uses: actions/upload-artifact@v4
              with:
                name: upload-multiple
                path: out/
            - uses: actions/download-artifact@v4
              with:
                name: upload-multiple
                path: download-multiple/
            - run: |
                ls -R download-multiple
                cat download-multiple/*
    
    upload-options:
        runs-on: ubuntu-slim
        steps:
            - run: |
                mkdir -p out
                echo "Build 123" >> out/build_123.txt
            - uses: actions/upload-artifact@v4
              with:
                name: upload-options
                path: out123
                if-no-files-found: ignore
                retention-days: 1 # 90 days default
                compression-level: 0 # 0 to 9
                overwrite: false
                include-hidden-files: true #.coverage files
    
    upload-matrix:
        runs-on: ubuntu-slim
        strategy:
            matrix:
                version: [18,19,20]
        steps:
            - run: | 
                mkdir -p out
                echo "Build version is ${{matrix.version}}" > out/build_${{matrix.version}}.txt
            - uses: actions/upload-artifact@v4
              with: 
                name: build_${{matrix.version}}
                path: out/
            # - uses: actions/download-artifact@v4
            #   with:
            #     name: build_${{matrix.version}}
            #     path: matrix-download/
    
    download-matrix:
        runs-on: ubuntu-slim
        needs: upload-matrix
        steps:
            - uses: actions/download-artifact@v4
              with:
                pattern: build_*
                merge-files: true
                path: matrix-download/
            - run: |
                ls -R matrix-download
                cat matrix-download/build_*/*.txt
    
              
