name: Dependency Cache
on: [push, pull_request,workflow_dispatch]
defaults:
    run:
        working-directory: node-app
jobs:
    cache-basic:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            
            - name: node setup
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: cache libraries
              uses: actions/cache@v4
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{hashFiles('node-app/package-lock.json')}} # Linux-node-12354235
                restore-key: ${{runner.os}}-node
                    
            - name: npm continous integration 
              run: npm ci
            - run: npm test