name: Caching
on: [push, pull_request, workflow_dispatch]
defaults:
    run:
        working-directory: node-app
jobs:
    cache-basic:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: node setup
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: cache libraries
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{runner.os}}-nodejs2-${{hashFiles('node-app/package-lock.json')}} # Linux-node-q93048q093
                restore-keys: ${{runner.os}}-nodejs2

            - name: npm continous integration
              run: npm ci
            - run: npm test
              
    cache-advance:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: node setup
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: cache libraries
              id: cache-lib
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{runner.os}}-nodejs3-${{hashFiles('node-app/package-lock.json')}} # Linux-node-q93048q093
            
            - name: cached data is available
              if: steps.cache-lib.outputs.cache-hit == 'true'
              run: echo "cached libraries found"

            - name: npm continous integration
              run: npm ci
            - run: npm test
    
    cache-matrix:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: [18,19,20]
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: node setup
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.version}}
            - name: cache libraries
              id: cache-lib
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{runner.os}}-nodejs-${{matrix.version}}-${{hashFiles('node-app/package-lock.json')}} # Linux-node-20-q93048q093

            - name: npm continous integration
              run: npm ci
            - run: npm test
            