name: Expressions
on: [push, pull_request,workflow_dispatch]
jobs:
    conditional_checks:
        runs-on: ubuntu-latest
        outputs:
          coverage: ${{ steps.cov.outputs.value }}
        steps:
            - name: check for main branch
              if: github.ref == 'refs/heads/main'
              run: echo "Deploying to main branch"
            
            - name: check for event other than pull request
              if: github.event_name != 'pull_request'
              run: echo "Do not execute sonarqube, checkmarx"
            
            - name: check for stage branch
              if: github.ref == 'refs/heads/stage'
              run: 'Deploying to stage branch'
            
            - name: assign coverage score
              id: cov
              run: echo "value=80" >> $GITHUB_OUTPUT
    
    conditional_checks_deploy:
        runs-on: ubuntu-latest
        needs: conditional_checks
        steps:
            - name: validate coverage score
              if: needs.conditional_checks.outputs.coverage > 85
              run: echo "Approved to deploy to Dev environment"
    
    logical_checks:
        runs-on: ubuntu-latest
        steps:
            - name: check for push event and into main branch
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: echo "Deploying to Dev for push into main branch"
            
            - name: check for push event or into main branch
              if: github.ref == 'refs/heads/main' ||  github.event_name == 'pull_request'
              run: echo "Deploying to Dev for push into main branch usong any condition"
    
    string_checks:
        runs-on: ubuntu-latest
        steps:
            - name: skips test executions
              if: contains(github.event.head_commit.message, 'skips-test')
              run: echo "Skipping test cases execution"
            
            # github.ref -> refs/heads/main
            # github.ref_name -> main
            # feature/release_1 feature/release_2
            - name: branch name starts with feature
              if: startsWith(github.ref_name, 'feature')
              run: echo "Deploying to feature branch"
            
            - name: branch name ends with dev1
              if: endsWith(github.ref_name, 'dev1')
              run: echo "Deploying hotfix"
        