name: Expressions
on: [push, pull_request,workflow_dispatch]
jobs:
    conditional_checks:
        runs-on: ubuntu-latest
        outputs:
          coverage: ${{ steps.cov.outputs.value }}
          score: 1
        steps:
            - name: check for main branch
              if: github.ref == 'refs/heads/main'
              run: echo "Deploying to main branch"
            
            - name: check for event other than pull request
              if: github.event_name != 'pull_request'
              run: echo "Do not execute sonarqube, checkmarx"
            
            - name: check for stage branch
              if: github.ref == 'refs/heads/stage'
              run: 'Deploying to stage branch'
            
            - name: assign coverage score
              id: cov
              run: echo "value=80" >> $GITHUB_OUTPUT
    
    conditional_checks_deploy:
        runs-on: ubuntu-latest
        needs: conditional_checks
        steps:
            - name: validate coverage score
              if: needs.conditional_checks.outputs.coverage > 85
              run: echo "Approved to deploy to Dev environment"