name: "Github Actions practical"
on:
    workflow_dispatch: # manual trigger.
      inputs:
        ENV:
          description: "Target Environment"
          required: true
          type: choice
          options:
            - DEV
            - PROD
        
    push:
        branches: ["main"]
        paths: 
            - "src/**"
            - "readme.MD"
    pull_request: 
        branches: ["main"]
        types: ["opened","reopened","synchronize"]

env:
    APP_NAME: "Happy Learning"
jobs: # multiple jobs we can create to run either paraller or sequencial.
    print_message: # job1
        runs-on: ubuntu-latest
        steps:
            - name: "printing welcome message"
              run: echo "Welcome"
            - name: "printing second message"
              run: echo "Bye"
            - name: "multiple messages"
              run: |
                echo "1st message"
                echo "2nd message"
    
    variables: #job 2
        runs-on: ubuntu-slim
        environment: ${{ inputs.ENV }}
        env:
          APP_NAME: "HAPPY LEARNING"
        steps:
          - run: |
              echo "Application name is $APP_NAME"
          - run: |
              echo "Repository variable data:: ${{ vars.SYNC_APP }}"
              echo "Env variable :: ${{vars.INSTANCES}}"

